name: Strava Auto Post

on:
  schedule:
    # 分 時 日 月 星期
    # 31 15 代表 UTC 15:31，等於 HKT 星期日晚上 23:31
    # 0 代表星期日
    - cron: '31 15 * * 0'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run script
        env:
          STRAVA_COOKIES: ${{ secrets.STRAVA_COOKIES }}
        run: node index.js

      - name: Upload screenshot if failed
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: |
            *.png
            *.jpg
